"""
=========================================================
QORA AI
reports.py

AI Report Generator

Creates planner reports, executive summaries,
PDF-ready reports and presentation content.

=========================================================
"""

from datetime import datetime


class ReportGenerator:

    def __init__(self, analytics):

        """
        analytics = DashboardAnalytics object
        """

        self.analytics = analytics

    # =====================================================
    # REPORT HEADER
    # =====================================================

    def report_header(self):

        return f"""
=========================================================
NESTLE DOM OPTIMIZATION REPORT
=========================================================

Generated by : Qora AI

Generated On : {datetime.now().strftime("%d-%m-%Y %H:%M:%S")}

=========================================================
"""

    # =====================================================
    # EXECUTIVE SUMMARY
    # =====================================================

    def executive_summary(self):

        return f"""
EXECUTIVE SUMMARY

This dashboard provides an overview of the Digital Order
Management optimization system.

Key Highlights

• Total Orders :
{self.analytics.total_orders()}

• Revenue :
{self.analytics.total_revenue()}

• Fill Rate :
{self.analytics.average_fill_rate()}

• Shipping Cost :
{self.analytics.total_shipping_cost()}

• Carbon Emissions :
{self.analytics.average_carbon()}

• Best Warehouse :
{self.analytics.best_warehouse()}

• Best Plant :
{self.analytics.best_plant()}

Overall, the optimization improves customer service,
reduces logistics costs and supports sustainable
supply chain planning.
"""

    # =====================================================
    # KPI REPORT
    # =====================================================

    def kpi_report(self):

        kpi = self.analytics.dashboard_summary()

        report = "KEY PERFORMANCE INDICATORS\n\n"

        for key, value in kpi.items():

            report += f"{key} : {value}\n"

        return report

    # =====================================================
    # WAREHOUSE REPORT
    # =====================================================

    def warehouse_report(self):

        return f"""
WAREHOUSE PERFORMANCE

Best Warehouse :
{self.analytics.best_warehouse()}

Worst Warehouse :
{self.analytics.worst_warehouse()}

Highest Utilization :
{self.analytics.highest_utilization()}

Lowest Utilization :
{self.analytics.lowest_utilization()}

Highest Inventory :
{self.analytics.highest_inventory()}

Lowest Inventory :
{self.analytics.lowest_inventory()}
"""

    # =====================================================
    # PLANT REPORT
    # =====================================================

    def plant_report(self):

        return f"""
PLANT PERFORMANCE

Best Plant :
{self.analytics.best_plant()}

Worst Plant :
{self.analytics.worst_plant()}

Top Plants

{self.analytics.top_plants()}
"""
    
    # =====================================================
    # PLANNER REPORT
    # =====================================================

    def planner_report(self):

        report = self.report_header()

        report += "\n"

        report += self.executive_summary()

        report += "\n"

        report += self.kpi_report()

        report += "\n"

        report += self.warehouse_report()

        report += "\n"

        report += self.plant_report()

        report += "\n"

        report += """
=========================================================
PLANNER OBSERVATIONS
=========================================================

1. Monitor warehouse utilization regularly.

2. Maintain sufficient inventory levels.

3. Reduce transportation costs.

4. Improve Fill Rate whenever possible.

5. Balance warehouse workloads.

6. Optimize delivery routes.

7. Minimize carbon emissions.

8. Improve customer satisfaction.

9. Reduce penalty costs.

10. Continue using AI optimization for planning.
"""

        return report

    # =====================================================
    # AI INSIGHTS
    # =====================================================

    def ai_insights(self):

        insights = []

        insights.append(
            f"Best Warehouse : {self.analytics.best_warehouse()}"
        )

        insights.append(
            f"Best Plant : {self.analytics.best_plant()}"
        )

        insights.append(
            f"Top Product : {self.analytics.top_product()}"
        )

        insights.append(
            f"Average Fill Rate : {self.analytics.average_fill_rate()}"
        )

        insights.append(
            f"Average Carbon Emissions : {self.analytics.average_carbon()}"
        )

        insights.append(
            "AI recommends balancing warehouse utilization."
        )

        insights.append(
            "AI recommends reducing transportation distance."
        )

        insights.append(
            "AI recommends replenishing low inventory warehouses."
        )

        return insights

    # =====================================================
    # RECOMMENDATIONS REPORT
    # =====================================================

    def recommendation_report(self):

        report = "AI RECOMMENDATIONS\n\n"

        for item in self.ai_insights():

            report += f"• {item}\n"

        return report

    # =====================================================
    # PDF CONTENT
    # =====================================================

    def pdf_content(self):

        return (
            self.report_header()
            + "\n"
            + self.executive_summary()
            + "\n"
            + self.kpi_report()
            + "\n"
            + self.warehouse_report()
            + "\n"
            + self.plant_report()
            + "\n"
            + self.recommendation_report()
        )

    # =====================================================
    # POWERPOINT CONTENT
    # =====================================================

    def powerpoint_content(self):

        slides = []

        slides.append({
            "title": "Nestlé DOM Optimization",
            "content": "Executive Dashboard Report"
        })

        slides.append({
            "title": "Executive Summary",
            "content": self.executive_summary()
        })

        slides.append({
            "title": "KPIs",
            "content": self.kpi_report()
        })

        slides.append({
            "title": "Warehouse Performance",
            "content": self.warehouse_report()
        })

        slides.append({
            "title": "Plant Performance",
            "content": self.plant_report()
        })

        slides.append({
            "title": "AI Recommendations",
            "content": self.recommendation_report()
        })

        return slides
    
        # =====================================================
    # MARKDOWN REPORT
    # =====================================================

    def markdown_report(self):

        report = f"""
# Nestlé DOM Optimization Report

## Executive Summary

{self.executive_summary()}

---

## KPI Report

{self.kpi_report()}

---

## Warehouse Performance

{self.warehouse_report()}

---

## Plant Performance

{self.plant_report()}

---

## AI Recommendations

{self.recommendation_report()}
"""

        return report

    # =====================================================
    # HTML REPORT
    # =====================================================

    def html_report(self):

        html = f"""
<html>

<head>
<title>Nestlé DOM Report</title>
</head>

<body>

<h1>Nestlé DOM Optimization Report</h1>

<pre>

{self.planner_report()}

</pre>

</body>

</html>
"""

        return html

    # =====================================================
    # JSON EXPORT
    # =====================================================

    def json_report(self):

        return {

            "generated_by": "Qora AI",

            "executive_summary": self.executive_summary(),

            "kpis": self.analytics.dashboard_summary(),

            "warehouse_report": self.warehouse_report(),

            "plant_report": self.plant_report(),

            "recommendations": self.ai_insights()

        }

    # =====================================================
    # REPORT STATISTICS
    # =====================================================

    def report_statistics(self):

        return {

            "total_orders": self.analytics.total_orders(),

            "total_products": self.analytics.total_products(),

            "total_customers": self.analytics.total_customers(),

            "best_warehouse": self.analytics.best_warehouse(),

            "best_plant": self.analytics.best_plant(),

            "top_product": self.analytics.top_product()

        }

    # =====================================================
    # COMPLETE REPORT
    # =====================================================

    def generate_complete_report(self):

        return {

            "text": self.planner_report(),

            "pdf": self.pdf_content(),

            "markdown": self.markdown_report(),

            "html": self.html_report(),

            "json": self.json_report(),

            "slides": self.powerpoint_content(),

            "statistics": self.report_statistics()

        }

    # =====================================================
    # SAVE REPORT
    # =====================================================

    def save_text_report(self, filename="planner_report.txt"):

        with open(filename, "w", encoding="utf-8") as file:

            file.write(self.planner_report())

        return filename

    def save_markdown_report(self, filename="planner_report.md"):

        with open(filename, "w", encoding="utf-8") as file:

            file.write(self.markdown_report())

        return filename

    def save_html_report(self, filename="planner_report.html"):

        with open(filename, "w", encoding="utf-8") as file:

            file.write(self.html_report())

        return filename

# =====================================================
# END OF FILE
# =====================================================